name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    environment: development
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lock bundle
        run: |
          bundle lock --add-platform x86_64-darwin-20
        if: github.event_name == 'pull_request'

      - name: ruby versions
        run: |
          ruby --version
          gem --version
          bundler --version
        if: github.event_name == 'pull_request'

      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
        if: github.event_name == 'pull_request'

      # - name: Update rubygems
      #   run: |
      #     gem update --system 3.2.1
      #   if: github.event_name == 'pull_request'
      
      - name: Build & Test
        run: |
          xcodebuild test -testPlan TCAShowcaseTests -scheme TCAShowcaseTests -project 'TCAShowcase/TCAShowcase.xcodeproj' -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' -resultBundlePath TestsResult.xcresult
      
      - name: Archive failed snapshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: 'TCAShowcase/failed-snapshots'

      - name: danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          bundle exec danger --verbose
        if: github.event_name == 'pull_request'
